image: mcr.microsoft.com/dotnet/core/runtime

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script:
          - dotnet restore
          - dotnet build
          - dotnet test
